
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Jun 26 17:16:32 CEST 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR = 45;
  public static final int CONST = 5;
  public static final int NAMESPACE = 15;
  public static final int RBOXBRACK = 39;
  public static final int NOTEQUAL = 22;
  public static final int LPAREN = 36;
  public static final int GREATER = 23;
  public static final int SEMI = 32;
  public static final int CONTINUE = 12;
  public static final int LESS = 25;
  public static final int FOR = 13;
  public static final int MINUS = 17;
  public static final int RPAREN = 37;
  public static final int STATIC = 14;
  public static final int AND = 27;
  public static final int OR = 28;
  public static final int BOOL = 44;
  public static final int COMMA = 33;
  public static final int INC = 30;
  public static final int DBLCOLON = 42;
  public static final int DIV = 19;
  public static final int PLUS = 16;
  public static final int LESSEQ = 26;
  public static final int ASSIGN = 29;
  public static final int IF = 6;
  public static final int DOT = 35;
  public static final int EOF = 0;
  public static final int RETURN = 10;
  public static final int EQUAL = 21;
  public static final int NEW = 7;
  public static final int error = 1;
  public static final int MUL = 18;
  public static final int LBOXBRACK = 38;
  public static final int NUMBER = 43;
  public static final int MOD = 20;
  public static final int IDENT = 46;
  public static final int BREAK = 3;
  public static final int VOID = 11;
  public static final int COLON = 34;
  public static final int LBRACE = 40;
  public static final int ELSE = 4;
  public static final int READ = 9;
  public static final int RBRACE = 41;
  public static final int PROG = 2;
  public static final int GREATEREQ = 24;
  public static final int DEC = 31;
  public static final int PRINT = 8;
}

